quarkus:
  http:
    port: 5000
  devservices:
    enabled: false
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:tcp://localhost/mem:test
  hibernate-orm:
    database:
      generation: update